print("Choose any number :")
a = input("Press Enter after that :-")
print("Multiply it by 2")
a = input("Press Enter after that :-")
print("Add 10 to your total")
a = input("Press Enter after that :-")
print("Now, Divide your total by 2")
a = input("Press Enter after that :-")
print("Finally, Substract the total from the first number you picked")
a = input("Press Enter after that :-")
print("Your answer is 5")
